/**
 * songs.js — Your music catalog
 *
 * This is the file you'll edit most often — add, remove, or update
 * songs here. Each entry is one song object.
 *
 * Fields:
 *   id          {string}   Unique identifier — never reuse or change once set
 *   title       {string}   Song title
 *   artist      {string}   Artist name
 *   album       {string}   Album or EP name
 *   duration    {number}   Length in seconds (used for display only)
 *   src         {string}   Path or URL to the audio file
 *   artwork     {string}   Path or URL to the album art image (square recommended)
 *   tags        {string[]} Array of tag strings (lowercase, no spaces)
 *   notes       {string}   Lyrics, liner notes, or any freeform text
 *   dateAdded   {string}   ISO date string "YYYY-MM-DD" for sorting
 *   downloadable {boolean} Show download button for this track (true/false)
 *
 * Audio tips:
 *   — Put .mp3 files in the /audio/ folder and reference as "audio/filename.mp3"
 *   — For large files (>50MB), host on Google Drive and use the direct link:
 *     "https://drive.google.com/uc?export=download&id=YOUR_FILE_ID"
 *
 * Artwork tips:
 *   — Put images in the /art/ folder and reference as "art/filename.jpg"
 *   — Square images (e.g. 500×500px) work best in the card grid
 *   — External URLs (imgur, etc.) also work fine
 */

const SONGS = [
  {
    id: "s003",
    title: "Woo Hoo Smooching Fever",
    artist: "",
    album: "",
    duration: 290,
    src: "audio/Woo hoo.mp3",
    artwork: "art/woo-hoo.png",
    tags: ["precious brat"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s004",
    title: "Down by the Shore",
    artist: "",
    album: "",
    duration: 235,
    src: "audio/Down by the Shore.mp3",
    artwork: "art/down-by-the-shore.png",
    tags: ["portia"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s005",
    title: "Emotional Support Salmon",
    artist: "",
    album: "",
    duration: 136,
    src: "audio/Emotional Support Salmon.mp3",
    artwork: "art/emotional-support-salmon.png",
    tags: ["laurie"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s006",
    title: "Every Jess needs a Kristy",
    artist: "",
    album: "",
    duration: 253,
    src: "audio/Every Jess needs a Kristy.mp3",
    artwork: "art/every-jess-needs-a-kristy-remix.png",
    tags: ["jessica","kristy"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s007",
    title: "Every Song Needs Italo Disco",
    artist: "",
    album: "",
    duration: 222,
    src: "audio/Everysong Needs Italo Disco.mp3",
    artwork: "art/everysong_needs_italo_disco.png",
    tags: ["precious brat"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s008",
    title: "Gonna be all right",
    artist: "",
    album: "",
    duration: 242,
    src: "audio/Gonna be all right.mp3",
    artwork: "art/gonna_be_all_right.png",
    tags: ["allie"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s009",
    title: "Half Rescue, Half Riot",
    artist: "",
    album: "",
    duration: 205,
    src: "audio/Half Rescue, Half Riot.mp3",
    artwork: "art/half-rescue-half-riot.png",
    tags: ["jessica","kristy"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s010",
    title: "I Am but their Humble Servant",
    artist: "",
    album: "",
    duration: 168,
    src: "audio/I Am but their Humble Servant.mp3",
    artwork: "art/humble-servant.png",
    tags: ["jessica"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s011",
    title: "I want the Tiddies not the Responsibilities",
    artist: "",
    album: "",
    duration: 230,
    src: "audio/I want the Tiddies not the Responsibilities.mp3",
    artwork: "art/tiddies.png",
    tags: ["alice","kristy"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s012",
    title: "It's All Good in the Hood",
    artist: "",
    album: "",
    duration: 162,
    src: "audio/It's All Good in the Hood.mp3",
    artwork: "art/its-all-good-in-the-hood-cover.png",
    tags: ["candice"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s013",
    title: "Jenny",
    artist: "",
    album: "",
    duration: 210,
    src: "audio/Jenny.mp3",
    artwork: "art/jenny.png",
    tags: [],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s014",
    title: "Kaleidomancer",
    artist: "",
    album: "",
    duration: 174,
    src: "audio/Kaleidomancer.mp3",
    artwork: "art/kaleidomancer.png",
    tags: ["holly","alice"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s015",
    title: "Lady Nike and the Plundered Booty",
    artist: "",
    album: "",
    duration: 168,
    src: "audio/Lady Nike and the Plundered Booty.mp3",
    artwork: "art/sea-shanty.png",
    tags: [],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s016",
    title: "She was Left Unsupervised",
    artist: "",
    album: "",
    duration: 265,
    src: "audio/Left Unsupervised.mp3",
    artwork: "art/left-unsupervised-remastered.png",
    tags: ["kristy","jessica"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s017",
    title: "Safety Scarf",
    artist: "",
    album: "",
    duration: 185,
    src: "audio/Safety Scarf.mp3",
    artwork: "art/safety-scarf.png",
    tags: ["precious brat"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s018",
    title: "Sandy Cheeks",
    artist: "",
    album: "",
    duration: 165,
    src: "audio/Sandy Cheeks.mp3",
    artwork: "art/sandy-cheeks-remix.png",
    tags: ["alice"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s019",
    title: "Trixie has Space Crabs",
    artist: "",
    album: "",
    duration: 221,
    src: "audio/Space Crabs.mp3",
    artwork: "art/space-crabs.png",
    tags: ["trixie"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s020",
    title: "The land of TimBits",
    artist: "",
    album: "",
    duration: 229,
    src: "audio/The land of timbits.mp3",
    artwork: "art/Land-of-Timbits.png",
    tags: ["laurie"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s021",
    title: "The Universe Blinked and I Found You",
    artist: "",
    album: "",
    duration: 224,
    src: "audio/The Universe Blinked and I Found You.mp3",
    artwork: "art/universe-cover-cover-cover-cover.png",
    tags: ["holly", "alice"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s022",
    title: "Trixie's Prickly Precious",
    artist: "",
    album: "",
    duration: 244,
    src: "audio/Trixie's Prickly Precious.mp3",
    artwork: "art/trixie-precious.png",
    tags: ["trixie"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s023",
    title: "Whats in your coffee",
    artist: "",
    album: "",
    duration: 207,
    src: "audio/Whats in your coffee.mp3",
    artwork: "art/whats-in-your-coffee.png",
    tags: [],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s024",
    title: "She Froze Her Dingaling Off",
    artist: "",
    album: "",
    duration: 238,
    src: "audio/Winter's Bite.mp3",
    artwork: "art/winters-bite.png",
    tags: ["trixie"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s025",
    title: "Abi Shaped Hole",
    artist: "",
    album: "",
    duration: 161,
    src: "audio/Abi.mp3",
    artwork: "art/abi.png",
    tags: ["precious brat", "abi"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s026",
    title: "The Carpets Don't Match The Drapes",
    artist: "",
    album: "",
    duration: 217,
    src: "audio/Carpet Dont Match The Drapes.mp3",
    artwork: "art/redhead-cover.png",
    tags: ["kristy"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s027",
    title: "Dont Feed Trixie's Ego",
    artist: "",
    album: "",
    duration: 312,
    src: "audio/Dont Feed Trixie's Ego.mp3",
    artwork: "art/trixie-cover.png",
    tags: ["trixie"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s028",
    title: "Pam Queen of the Pole",
    artist: "",
    album: "",
    duration: 170,
    src: "audio/Pam Queen of the Pole.mp3",
    artwork: "art/pam.png",
    tags: [],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s029",
    title: "Hollyween",
    artist: "",
    album: "",
    duration: 262,
    src: "audio/Hollyween.mp3",
    artwork: "art/hollyween.png",
    tags: ["holly"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s030",
    title: "Laurie and Her Salmon Squad",
    artist: "",
    album: "",
    duration: 362,
    src: "audio/Laurie and Her Salmon Squad.mp3",
    artwork: "art/Laurie and Her Salmon Squad.png",
    tags: ["laurie"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s031",
    title: "Laurie Took over a Tim Horton's",
    artist: "",
    album: "",
    duration: 304,
    src: "audio/Laurie Took over Tim Hortons.mp3",
    artwork: "art/Laurie Took over Tim Hortons.png",
    tags: ["laurie"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s032",
    title: "Pile of Jessicas",
    artist: "",
    album: "",
    duration: 214,
    src: "audio/Pile of Jessicas .mp3",
    artwork: "art/pile-of-jessicas.png",
    tags: ["jessica", "kristy"],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s033",
    title: "Pom Poms and Razor Blades",
    artist: "",
    album: "",
    duration: 239,
    src: "audio/Pom Poms and Razor Blades.mp3",
    artwork: "art/pom-poms-and-razor-blades.png",
    tags: [],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s034",
    title: "The Prettiest Dommie",
    artist: "",
    album: "",
    duration: 250,
    src: "audio/The Prettiest Dommie.mp3",
    artwork: "art/prettiest-dommie-remix.png",
    tags: [],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s035",
    title: "TWERKGEDDON: The Ballad of the Sanctified Sapphics",
    artist: "",
    album: "",
    duration: 249,
    src: "audio/TWERKGEDDON_ The Ballad of the Sanctified Sapphics.mp3",
    artwork: "art/twerkgeddon-the-ballad-of-the-sanctified-sapphics.png",
    tags: [],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s036",
    title: "Zizi of the Sea",
    artist: "",
    album: "",
    duration: 235,
    src: "audio/Zizi of the Sea.mp3",
    artwork: "art/zizi-of-the-sea.png",
    tags: [],
    notes: "",
    dateAdded: "2026-03-17",
    downloadable: true,
  },

  {
    id: "s037",
    title: "Trixie has rabies",
    artist: "",
    album: "",
    duration: 210,
    src: "audio/Trixie has rabies.mp3",
    artwork: "art/trixie-has-rabies.png",
    tags: ["trixie"],
    notes: "",
    dateAdded: "2026-03-20",
    downloadable: true,
  },

  {
    id: "s038",
    title: "It's Pie",
    artist: "",
    album: "",
    duration: 270,
    src: "audio/It's Pie.mp3",
    artwork: "art/its_pie.png",
    tags: [],
    notes: "",
    dateAdded: "2026-03-25",
    downloadable: true,
  },

  {
    id: "s039",
    title: "Amanda Beth's Sunshine Shoppe",
    artist: "",
    album: "",
    duration: 171,
    src: "audio/Amanda Beth's Sunshine Shoppe.mp3",
    artwork: "art/20240704amanda-beths-sunshine-shoppe.png",
    tags: [],
    notes: "",
    dateAdded: "2026-03-27",
    downloadable: true,
  },
  {
    id: "s040",
    title: "She twerked at my girl, now I gotta ruin her",
    artist: "",
    album: "",
    duration: 204,
    src: "audio/She Twerked at My Girl, Now I gotta Ruin Her.mp3",
    artwork: "art/twerked.png",
    tags: ["jessica","kristy"],
    notes: "",
    dateAdded: "2026-03-27",
    downloadable: true,
  },
  {
    id: "s041",
    title: "The Sweet Life",
    artist: "",
    album: "",
    duration: 240,
    src: "audio/Sweet Life.mp3",
    artwork: "art/sweet_life.png",
    tags: [],
    notes: "",
    dateAdded: "2026-04-1",
    downloadable: true,
  },
  {
    id: "s042",
    title: "Somewhere there's a Vespa waiting for me",
    artist: "",
    album: "",
    duration: 248,
    src: "audio/Somewhere there's a vespa waiting for me.mp3",
    artwork: "art/vespa.png",
    tags: ["precious brat"],
    notes: "",
    dateAdded: "2026-04-1",
    downloadable: true,
  },
];
